export const DEFAULT_FOLDER_ICON = "FolderOpen";

export const ICON_CATEGORIES = {
  folders: [
    "FolderOpen",
    "Folder",
    "FolderPlus",
    "FolderHeart",
    "FolderLock",
    "FolderKey",
    "FolderDown",
    "FolderUp",
    "FolderGit2",
    "FolderKanban",
    "FolderSync",
    "FolderTree",
  ],
  files: [
    "File",
    "FileText",
    "FileImage",
    "FileCode",
    "FileArchive",
    "FileJson",
    "FilePieChart",
    "FileSpreadsheet",
    "FileVideo",
    "FileAudio",
    "FileCheck",
    "FileClock",
    "FileEdit",
    "FileSearch",
    "FileX",
  ],
  shapes: [
    "Circle",
    "Square",
    "Triangle",
    "Hexagon",
    "Pentagon",
    "Star",
    "Heart",
    "Diamond",
    "Octagon",
    "Aperture",
  ],
  ui: [
    "Bookmark",
    "Flag",
    "Tag",
    "Target",
    "BadgeCheck",
    "BadgeHelp",
    "BadgeInfo",
    "BadgeAlert",
    "Pin",
    "PinOff",
  ],
  tools: [
    "Archive",
    "Box",
    "Package",
    "Layers",
    "Package2",
    "PackageOpen",
    "PackageSearch",
    "ArchiveRestore",
    "ArchiveX",
    "CandyOff",
  ],
  business: [
    "Briefcase",
    "Building",
    "Building2",
    "CreditCard",
    "DollarSign",
    "Receipt",
    "ChartBar",
    "ChartPie",
    "TrendingUp",
    "TrendingDown",
  ],
  creative: [
    "Palette",
    "Brush",
    "Pen",
    "PenTool",
    "Highlighter",
    "Eraser",
    "Camera",
    "Image",
    "Images",
    "Film",
  ],
  tech: [
    "Cpu",
    "Server",
    "Database",
    "HardDrive",
    "Wifi",
    "Bluetooth",
    "Usb",
    "Monitor",
    "Laptop",
    "Smartphone",
  ],
  misc: [
    "Wrench",
    "Settings",
    "Cog",
    "Sliders",
    "Sparkles",
    "Zap",
    "Flame",
    "Sun",
    "Moon",
    "Cloud",
  ],
} as const;

export const POPULAR_ICONS = [
  ...ICON_CATEGORIES.folders,
  ...ICON_CATEGORIES.files,
  ...ICON_CATEGORIES.shapes,
  ...ICON_CATEGORIES.ui,
  ...ICON_CATEGORIES.tools,
  ...ICON_CATEGORIES.business,
  ...ICON_CATEGORIES.creative,
  ...ICON_CATEGORIES.tech,
  ...ICON_CATEGORIES.misc,
];

export type IconCategory = keyof typeof ICON_CATEGORIES;
export type IconName = (typeof POPULAR_ICONS)[number];
